<?php
include'../../../conexion.php';

$id = $_GET['id'];
$sql = "SELECT idusuarios, nombres_usuarios, apellidos_usuarios, genero_usuarios, idclasificacionusuarios, tipo_documento_usuarios, numero_documento_usuarios,direccion_usuarios, 
telefono_usuarios, ciudad_usuarios, correo_usuarios, nombre_usuario, observaciones_usuarios, clave1_usuarios, estado_usuarios FROM tab_usuarios
WHERE idusuarios='$id' ";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
?>
  <!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar</title>
    <!-- Fonts and icons -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="material-dashboard1.css">
    <script src="dist/sweetalert2.all.min.js"></script>
  </head>

  </head>

  <body>

    <!-- End Navbar -->
    <style>
      /* Background styles */
      body {
        background-image: url('https://p4.wallpaperbetter.com/wallpaper/909/149/238/vehicles-motorcycle-motogp-hd-wallpaper-preview.jpg');
        background-position: left;
      }

      /* Glassmorphism card effect */
      .card {
        backdrop-filter: blur(16px) saturate(200%);
        -webkit-backdrop-filter: blur(16px) saturate(200%);
        background-color: #78787800;
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.125);

      }

      .form-check,
      label {
        font-size: 14px;
        line-height: 1.42857;
        color: #ffffff;
        font-weight: 400;
      }


      /* Generated by https://generator.ui.glass/ */
    </style>
    <center>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-text card-header-danger">
            <div class="card-text">
              <h4 class="card-title"> Formulario Actualización Usuarios</h4>
            </div>
          </div>
          <br>
          <div class="card-body">
            <?php
            while ($row = $result->fetch_assoc()) {
            ?>
              <form class="was-validated" method="POST" action="procesar.php">
                <form class="needs-validation " novalidate>
                  <div class="form-row">
                    <div class="col-md-6 mb-3">
                      <input type="hidden" value="<?php echo  $row["idusuarios"]; ?>" name="txtid">
                      <label for="validationCustom01" class="md-label-floating">Nombres</label>
                      <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["nombres_usuarios"]; ?>" required minlength="1" maxlength="150" pattern="[a-zA-Z ]+" name="txtnombres">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom02">Apellidos</label>
                      <input type="text" class="form-control" id="validationCustom02" value="<?php echo  $row["apellidos_usuarios"]; ?>" required minlength="1" maxlength="150" pattern="[a-zA-Z ]+" name="txtapellidos">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                  </div>
                  <div class="form-group" class>
                    <label for="exampleFormControlSelect1">Genero</label>
                    <select class="custom-select" required name="txtgenero">
                      <option name="idgenero" value="">Seleccionar Genero</option>
                      <option name="idgenero" value="masculino">Masculino </option>
                      <option name="idgenero" value="femenino">Femenino</option>
                      <option name="idgenero" value="otro">Otro</option>
                    </select>
                    <div class="invalid-feedback">Genero no seleccionada</div>
                  </div>
                  <div class="form-group" class>
                    <label for="exampleFormControlSelect1">Cargo</label>
                    <select class="custom-select" required name="txtcargo">
                      <option name="idcargo" value="">Seleccionar Cargo</option>
                      <option name="idcargo" value="1">Cliente</option>
                      <option name="idcargo" value="2">Vendedor</option>
                      <option name="idcargo" value="3">Administrador</option>
                    </select>
                    <div class="invalid-feedback">Cargo no seleccionada</div>
                  </div>
                  <div class="form-group" class>
                    <label for="exampleFormControlSelect1">Tipo de Documento</label>
                    <select class="custom-select" required name="txttipodocumento">
                      <option name="iddocumento" value="">Seleccionar Tipo de Documento</option>
                      <option name="iddocumento" value="cedula ciudadania">Cedula de Ciudadania </option>
                      <option name="iddocumento" value="Tarjeta Identidad">Tarjeta de Identidad</option>
                      <option name="iddocumento" value="cedula extranjera">Cedula de Extranjera</option>
                      <option name="iddocumento" value="registro civil">Registro Civil</option>
                    </select>
                    <div class="invalid-feedback">Tipo de Documento No Seleccionado</div>
                  </div>
                  <br>
                  <div class="form-row">
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom01" class="md-label-floating">Numero de Documento</label>
                      <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["numero_documento_usuarios"]; ?>" required minlength="1" maxlength="150" pattern="[0-9 ]+" name="txtnumerodocumento">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom02">Direccion</label>
                      <input type="text" class="form-control" id="validationCustom02" value="<?php echo  $row["direccion_usuarios"]; ?>" required minlength="1" maxlength="150" pattern="[a-zA-Z0-9 ]*$+" name="txtdireccion">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom01" class="md-label-floating">Telefono</label>
                      <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["telefono_usuarios"]; ?>" required minlength="1" maxlength="150" pattern="[0-9 ]+" name="txttelefono">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom02">Ciudad</label>
                      <input type="text" class="form-control" id="validationCustom02" value="<?php echo  $row["ciudad_usuarios"]; ?>" required minlength="1" maxlength="150" pattern="[a-zA-Z ]+" name="txtciudad">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom01" class="md-label-floating"> Correo Electronico</label>
                      <input type="email" class="form-control" required name="txtcorreo" value="<?php echo  $row["correo_usuarios"]; ?>">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom02"> Nombre Usuario</label>
                      <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["nombre_usuario"]; ?>" required minlength="5" maxlength="30" pattern="[a-zA-Z0-9 ]+" name="txtnombreusuario">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                  </div>

                  <div class="form-row">
                    <div class="col-md-6 mb-3">
                      <label for="validationCustom02">Observaciones</label>
                      <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["observaciones_usuarios"]; ?>" required minlength="5" maxlength="30" pattern="[a-zA-Z0-9 ]+" name="txtobservaciones">
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                    <div class="col-md-6 mb-3">
                      <label for="examplePassword" class="md-label-floating">Contraseña</label>
                      <input type="password" class="form-control" id="password" title="password" required minlength="5" maxlength="10" name="txtpassword1" value="">
                      <button type="button" id="mostrar" class="btn btn-success btn-fab btn-round">
                        <i class="material-icons">visibility_off</i>
                        <div class="ripple-container">
                        </div>
                      </button>
                      <div class="valid-feedback">
                        ¡Campo Ok!
                      </div>
                      <div class="invalid-feedback">
                        ¡Corregir Campo!
                      </div>
                    </div>
                  </div>

                  <div class="form-group" class>
                    <label for="exampleFormControlSelect1">Estado de Usuario</label>
                    <select class="custom-select" required name="txtestado">
                      <option name="estado" value="">Seleccionar Estado</option>
                      <option name="estado" value="1">Activo</option>
                      <option name="estado" value="0">Desactivado</option>
                    </select>
                    <div class="invalid-feedback">Cargo no seleccionada</div>
                  </div>
                  <button type="submit" class="btn btn-success" name="registro">Actualizacion Usuarios </button><a href="/material1/proyecto_principal/crud_usuarios/administrador/crud_administrador.php" class="btn btn-info " role="button" aria-pressed="true">Regresar</a>
                </form>
          </div>
      <?php
            }
          }
      ?>
  </body>
  <script>
    // primero seleccionamos el elemento id del button
    mostrar.addEventListener("mousedown", () => {
      // Eliminamos su type del input
      password.removeAttribute("type");
    });
    mostrar.addEventListener("mouseup", () => {
      // Agregamos type de input
      password.setAttribute("type", "password");
    });
  </script>
  </body>

  </html>