<?php
include '../../conexion.php';

$id = $_GET['id'];
$sql = "SELECT  idmensajes, observaciones_mensajes FROM tab_mensajes WHERE idmensajes='$id'";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
?>
  <!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar</title>
    <!-- Fonts and icons -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="material-dashboard1.css">
    <script src="dist/sweetalert2.all.min.js"></script>
  </head>

  </head>

  <body>

    <!-- End Navbar -->
    <style>
      /* Background styles */
      body {
        background-image: url('https://res.cloudinary.com/dte7upwcr/image/upload/f_auto,w_1500/blog/blog2/atencion-premera-posicion/herramientas-atencion-cliente-jivochat.png');
        background-position: center;
      }

      /* Glassmorphism card effect */
      .card {
        backdrop-filter: blur(25px) saturate(200%);
        -webkit-backdrop-filter: blur(25px) saturate(200%);
        background-color: #333333b5;
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.125);
      }

      .form-control[readonly] {
        background-color: #55585a5e;
        opacity: 1;
      }

      /* Generated by https://generator.ui.glass/ */
    </style>
    <center>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-text card-header-warning">
            <div class="card-text">
              <h4 class="card-title">Formulario Actualizacion de Mensajes</h4>
            </div>
          </div>
          <br>
          <?php
          while ($row = $result->fetch_assoc()) {
          ?>
            <div class="card-body">
              <form class="was-validated" method="POST" action="procesar.php">
                <form class="needs-validation " novalidate>
                    <div class="container">                      
                        <div class="col-md-6 mb-3">
                          <input type="hidden" value="<?php echo  $row["idmensajes"]; ?>" name="txtid">
                          <label for="validationCustom02">Observaciones</label>
                          <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["observaciones_mensajes"]; ?>" required minlength="5" maxlength="30" pattern="[a-zA-Z0-9 ]+" name="txtobservaciones">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                       </div>
                      <button type="submit" class="btn btn-success" name="registro">Actualizacion Mensajes </button>
                      <a href="/material1/proyecto_principal/crud_mensajes/crud_mensajes.php" class="btn btn-warning " role="button" aria-pressed="true">Regresar</a>
                    </div>
                  </div>
            </div>
            </form>
            </form>
        <?php
          }
        }
        ?>
  </body>

  </html>