<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="https://logodownload.org/wp-content/uploads/2017/04/suzuki-logo-1-1.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Susuki Motos
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="../assets/css/material-kit2.css" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
   <style type="text/css">
.boton {
    padding: 8px 25px;
    background: #448AFF;
    color: #fff;
    border-radius: 4px;
    text-decoration:none;
}
  </style>

</head>

<body class="login-page sidebar-collapse">

  <div class="page-header header-filter"
    style="background-image: url('../assets/img/foto.png'); background-size: 1400px 900px; background-position: top center; opacity: 0.8;">
    <style>
      /* Background styles */
      body {
        background-image: url('https://www.teahub.io/photos/full/212-2124948_imagens-hd-4k-motos.jpg');
        background-position: center;
      }

      /* Glassmorphism card effect */
      .card {
        backdrop-filter: blur(25px) saturate(200%);
        -webkit-backdrop-filter: blur(25px) saturate(200%);
        background-color: rgb(0, 0, 0);
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.125);
      }

      /* Generated by https://generator.ui.glass/ */
    </style>
    
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6 ml-auto mr-auto">
          <div class="card card-login">
            <form class="form" method="POST" action="registro_login2.php">
              <div class="card-header card-header-primary text-center">
                <img src="../assets/img/foto2.png" alt="logo" style="width:120px;height:100px;">
                <div class="social-line">
                  <a href="#pablo" class="btn btn-just-icon btn-link">
                    <i class="fa fa-facebook-square"></i>
                  </a>
                  <a href="#pablo" class="btn btn-just-icon btn-link">
                    <i class="fa fa-twitter"></i>
                  </a>
                  <a href="#pablo" class="btn btn-just-icon btn-link">
                    <i class="fa fa-google-plus"></i>
                  </a>
                </div>
              </div>
              <p class="description text-center">Ingreso a la Plataforma Vendedor</p>
              <div class="card-body">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="material-icons">face</i>
                    </span>
                  </div>
                  <input type="text" class="form-control" placeholder="Nombre Usuario..." name="txtingreso">
                </div>

                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="material-icons">lock_outline</i>
                    </span>
                  </div>
                  <input type="password" id="password" class="form-control" placeholder="Contraseña..." name="txtclave1">
                  <div class="form-group text-center">
                    <button type="button" id="mostrar"class="btn btn-warning btn-fab btn-round">
                      <i class="material-icons">visibility_off</i>
                    <div class="ripple-container">
                    </div></button>
                  </div>
                </div>

              </div>
              <div class="footer text-center">
                 <button type="submit" class="btn btn-primary btn-success btn-wd btn-warning" name="login">iniciar</button>
              </div>
               </div> 
              <center> 
              <a href="/material1/index.html" class="boton"><b>Regresar</b></a>
              </center>
            </form>
          </div>
        </div>
      </div>
    </div>

    <script>
      // primero seleccionamos el elemento id del button
      mostrar.addEventListener("mousedown", () => {
        // Eliminamos su type del input
        password.removeAttribute("type");
      });
      mostrar.addEventListener("mouseup", () => {
        // Agregamos type de input
        password.setAttribute("type", "password");
      });
    </script>
    
    <!--   Core JS Files   -->
    <script src="../assets/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
    <script src="../assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="../assets/js/plugins/moment.min.js"></script>
    <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
    <script src="../assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="../assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
    <!--  Google Maps Plugin    -->
    <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
    <script src="../assets/js/material-kit.js?v=2.0.7" type="text/javascript"></script>
</body>

</html>