<?php
include'../../../conexion.php';

$id = $_GET['id'];
$sql = "SELECT idusuarios, nombres_usuarios, apellidos_usuarios, idclasificacionusuarios, direccion_usuarios, telefono_usuarios, ciudad_usuarios, correo_usuarios FROM tab_usuarios
WHERE idusuarios='$id' ";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
?>

  <!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Automaticas</title>
    <!-- Fonts and icons -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="material-dashboard1.css">
    <script src="dist/sweetalert2.all.min.js"></script>
  </head>

  </head>

  <body>

    <!-- End Navbar -->
    <style>
      /* Background styles */
      body {
        background-image: url('https://www.teahub.io/photos/full/29-295735_gsx-r-750-2011-fondo-de-escritorio-wallpaper.jpg');
        background-position: center;
      }

      /* Glassmorphism card effect */
      .card {
        backdrop-filter: blur(25px) saturate(200%);
        -webkit-backdrop-filter: blur(25px) saturate(200%);
        background-color:#78787800;
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.125);
      }
      .form-check,
      label {
        font-size: 14px;
        line-height: 1.42857;
        color: #ffffff;
        font-weight: 400;
      }


      /* Generated by https://generator.ui.glass/ */
    </style>
    <center>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-text card-header-danger">
            <div class="card-text">
              <h4 class="card-title">Tabla de Usuario</h4>
            </div>
          </div>
          <br>
          <?php
          while ($row = $result->fetch_assoc()) {
          ?>
            <div class="card-body">
              <form class="was-validatedmethod=" method="POST" action="procesar.php">
                <form class="needs-validation " novalidate>
                  <div class="form-row">
                    <div class="container">
                      <div class="form-row">
                        <div class="col-md-6 mb-3">
                          <label for="validationCustom01" class="md-label-floating">Nombres</label>
                          <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["nombres_usuarios"]; ?>" name="txtnombres">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                        <div class="col-md-6 mb-3">
                          <label for="validationCustom02">Color</label>
                          <input type="text" class="form-control" id="validationCustom02" value="<?php echo  $row["apellidos_usuarios"]; ?>" name="txtapellidos">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                      </div>
                      <div class="form-row">
                        <div class="col-md-6 mb-3">
                          <label for="validationCustom01" class="md-label-floating">Direccion</label>
                          <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["direccion_usuarios"]; ?>" name="txtdireccion">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                        <div class="col-md-6 mb-3">
                          <label for="validationCustom02">Telefono</label>
                          <input type="text" class="form-control" id="validationCustom02" value="<?php echo  $row["telefono_usuarios"]; ?>" name="txttelefono">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                      </div>
                      <div class="form-row">
                        <div class="col-md-6 mb-3">
                          <label for="validationCustom01" class="md-label-floating">Ciudad</label>
                          <input type="text" class="form-control" id="validationCustom01" value="<?php echo  $row["ciudad_usuarios"]; ?>" name="txtciudad">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                        <div class="col-md-6 mb-3">
                          <label for="validationCustom02">Correo</label>
                          <input type="text" class="form-control" id="validationCustom02" value="<?php echo  $row["correo_usuarios"]; ?>" name="txtcorreo">
                          <div class="valid-feedback">
                            ¡Campo Ok!
                          </div>
                          <div class="invalid-feedback">
                            ¡Corregir Campo!
                          </div>
                        </div>
                      </div>
                      <input type="hidden" value="<?php echo  $row["idusuarios"]; ?>" name="txtid">
                      <input type="hidden" value="<?php echo  $row["idclasificacionusuarios"]; ?>" name="txtidclasificacion">



                      <button type="submit" name="guardar" class="btn btn-success">Actualizar</button>
                      <a href="/material1/proyecto_principal/crud_usuarios/vendedor/crud_clientes_vendedor.php" class="btn btn-info " role="button" aria-pressed="true">Regresar</a>
    </center>
    </form>
<?php
          }
        }
?>
  </body>

  </html>